import type { Metadata } from "next";
import { Manrope, Quicksand } from 'next/font/google';
import './globals.css';

const base_font = Manrope({ subsets: ['latin'] });
const accent_font = Quicksand({
  subsets: ['latin'],
  variable: '--font-accent',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${base_font.className} ${accent_font.variable}`}>
        {children}
      </body>
    </html>
  );
}
